### ISSUE TITLE
Temperature conversion error for <0°C 

### ISSUE THREAD

**Issue by bop0815** [nadavmatalon/MCP9802#7]
Hi, 
I'm getting wrong temperature values for temperatures lower than 0°C. 
Resulting in conversions results like 255°C.
Following code was used to get values from MCP9802:

```
const byte DEV_ADDR = 0x48;  
float temp;                          
MCP9802 mcp9802(DEV_ADDR);
mcp9802.setResolution(RES_12);
mcp9802.setConMode(SINGLE);
temp = mcp9802.singleCon();
```

**Comment by nadavmatalon** [comment]
Hi bop0815,

Thanks for bringing it to my attention.

I suspect the issue relates to the data-to-temp conversion algorithms (rather than the actual data reading algorithms), but will need to dive back into the code to find out. Might take a bit of time, though, as things are very busy at the moment with other projects. In the meantime, if you get a chance to pinpoint the bug, drop me a line and that will make the process quicker.

On a side-note, while working with the MCP9802 my impression was that the 'single conversion' mechanism of this chip isn't implemented as well as it could be and it is much better to work with the 'continuous conversion' mode whenever possible (unless there are compelling reasons to use the 'single' mode for a particular application of course).

All the best,
Nadav

**Comment by bop0815** [comment]
Hi Nadav,
first of all thank you for providing the library and an answer to my issue.

I looked into the code and changed the getData() function:
```
float MCP9802::getData(reg_ptr_t ptr) {  // PARAMS: TEMP / HYST / LIMIT
    int16_t raw_data;
	float data = 0;
    initCall(ptr);
    endCall();
    if (_comBuffer == COM_SUCCESS) {
        Wire.requestFrom(_devAddr, DATA_BYTES);
        if (Wire.available() == DATA_BYTES) raw_data = (((Wire.read() << 8) | (Wire.read())));
		data = (float)raw_data / 256.0;
	}

    return _tempUnit ? convertCtoF(data) : data;
}
```
Probably this was some data type problem. 
For me this solution worked out: now my sensor shows negative values 

Regarding single conversion: I have to admit I'm using your library with an ESP8266 for uploading temperature values to ThinkSpeak. In order to keep battery life acceptable, the ESP8266 is in deep sleep mode for most of the time. When it wakes up it issues a single temperature conversion, uploads it and continue sleeping. I've chosen the single conversion in the hope that the sensor will also stay in a lower power mode while not converting. Upto now the sensor uploaded around 2000 temperature samples, for me the single conversion seems to work fine. 

Best wishes from freezing cold Germany (-2°C)  ;)  
bop0815

**Comment by nadavmatalon** [comment]
Hi bop0815,

First, apologies for the long delay in getting back to you. 

Well done for tracing this bug! I'm very glad you caught it. As you say, it's definitely a mistake on my part with regard to the data-type (float instead of int16_t) and your solution looks solid 👍

I could just update the source code to fix this, but why don't we do it 'the Github way'? That is, if you make a pull-request with your correction, I'll merge it into the existing code. This way you'll get credit for the time/work you've put into this which you certainly deserve. Sounds good?

All the best & thanks again,
Nadav

**Comment by nadavmatalon** [comment]
Correction implemented and issue closed. Thanks bop0815!
